### ISSUE TITLE
High memory usage with Northern Tracks

### ISSUE THREAD

**Issue by mlincett** [icecube/flarestack#209]
Running analysis with Northern Tracks requires very large amounts of memory, approximately 10 GB per season. This seems to be related to the injector instances. A test job for a stacking using 2017-2021 seasons results in the following:
```
 Max vmem         = 49.945G
 Max rss          = 47.731G
```
This makes it hardly sustainable for the use on a cluster and even on a shared worker machine it could make people unhappy.

I am not sure how this can be improved, feedback is welcome!

**Comment by mlincett** [comment]
After chatting with @JannisNe , it seems that adding all IC86 seasons as a combined season (like it is done for PSTracks) could solve the issue (a single injector will be instantiated). Not sure about possible deeper implications, but I will try to run a quick comparison.

**Comment by mlincett** [comment]
Combining all seasons into a single one reduces the required memory as expected. The disadvantage is that the entire experimental dataset has to be loaded (making somehow ineffective the use of a _custom dataset_).

Results are compatible (let's say almost identical when tested with just a few trials) across the two options.

Taking quick `grep` at the source code, it seems subseasons are not implicitly used anywhere (but they could be used as individual datasets if the user wants to). 

I am now implementing NT v4p1 and I am considering just add a combined season plus subseasons, dropping the individual season schema we used for v4p0. Please advise ;)

**Comment by robertdstein** [comment]
I am a bit confused by this, maybe I misunderstood something. The dataset is divided into discrete "blocks", with each needing its own llh/injector. The reason is that each should correspond to a unique detector configuration, and therefore a unique Monte Carlo dataset. Therefore, post-detector-construction, individual IC seasons should be aggregated assuming the event selection was the same for all of them. Conventionally the independent event selections are IC40, IC59, IC79, IC86-I and then all IC86-II onwards should be aggregated. The reason is that the detector trigger setting changed between IC86-I and IC86-II despite no physical geometry change.

However, again, there is no hard and fast rule. The IC datasets each have corresponding MC datasets. There should be one injector per MC dataset. So @mlincett, what was the processing for NT V5? What seasons does it cover, and is there only one MC dataset?
