### ISSUE TITLE
Transition `DESYSubmitter` to `HTCondor`

### ISSUE THREAD

**Issue by JannisNe** [icecube/flarestack#219]
This is not a bug yet but will be at the end of the year. The DESY frame will transition from `gridengine` to `HTCondor` so the `DESYSubmitter` will stop working. Fortunately the `WIPACSubmitter` is already set up to use `HTCondor` so it will not be much work to mimic that for DESY. I will be working on this [here](https://github.com/icecube/flarestack/tree/desy_htcondor) and open a pull request asap.

**Comment by mlincett** [comment]
Thank you. Wanted to open an issue about this but nice to see you are already on it!

**Comment by mlincett** [comment]
Thanks @JannisNe for working on this. I am willing to test this branch and see what's left to do. Can you comment on the current state of progress?

**Comment by mlincett** [comment]
After a chat with @JannisNe it seems all is in place. We just need a better strategy to deal with log files. 

I suggest to drop the following from `flarestack/cluster`:
- `make_desy_cluster_script.py`
- `run_desy_cluster.py`

**Comment by mlincett** [comment]
I have adjusted the log paths so the log/err/out files are created under the `flarestack` scratch dir as initially intended.

Since for WIPAC it is not recommended to create HTCondor logs on network storage, I decoupled the path of log files from the one of out/err, so the former is overridden in `WIPACSubmitter`.

Everything should be ready.
