### ISSUE TITLE
Support python 3.11 in CI

### ISSUE THREAD

**Issue by mlincett** [icecube/flarestack#261]
We should add python 3.11 in CI.

Currently there may be some problems (see https://github.com/python-poetry/poetry/issues/7686) due to `poetry` being picky about invalid wheel files.

Also we should decide how many versions of `python` we should keep testing against.

**Comment by mlincett** [comment]
Issue at debugpy: https://github.com/microsoft/debugpy/issues/1246

**Comment by robertdstein** [comment]
I'm not sure what the best thing here is. We could edit the CI to do the "modern installer = False" option, or pin poetry 1.4.0. I have the impression that poetry will not "fix this" in future versions, since they view it as a check and the upstream repos like debugpy are the source of the problem because their wheels aren't correctly generated.  

On the python versions point, I would think it makes sense to test all the ones we currently do, since that costs nothing, but to not commit to maintaining compatibility. As soon as we have a good reason to drop an old version, e.g new-style code incompatible with e.g python 3.8, then we should just drop that version.

**Comment by mlincett** [comment]
Thanks for the feedback @robertdstein . I was honestly thinking of sitting on this for a reasonable amount of time to see whether the situation can be resolved upstream without us having to implement and follow-up workarounds. It seems Microsoft is aware there's an issuel, they just mentioned it's high priority.

**Comment by mlincett** [comment]
Seems the issues are fixed upstream, so I am merging the pending PR now.

Will add 3.12 as soon as `setup-python` will support it.
